name: Post processing of PR

on:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

jobs:

  close-issue:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature/') }}

    steps:
    
    - name: Clone a repo
      run: git clone https://github.com/begyyal/act_access_ghra.git

    - name: Prepare vars
      id: ready
      shell: bash
      run: |
        issue_url_base=${{ github.event.pull_request.issue_url }}
        branch=${{ github.head_ref }}
        echo "::set-output name=issue-url::${issue_url_base%/*}/${branch#feature/}"

    - name: Close issue
      uses: ./act_access_ghra
      with:
        url: ${{ steps.ready.outputs.issue-url }}
        method: 'PATCH'
        args: '{"state":"closed"}'
