name: Create feature branch

on:
  issues:
    types: [ opened ]

jobs:

  main:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        ref: develop
    
    - name: Create branch
      run: |
        git checkout -b feature/${{ github.event.issue.number }}
        git push origin feature/${{ github.event.issue.number }}
