name: CI

on:
  push:
    branches: [ develop ]

jobs:

  dev-ci:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Prepare conditions
      id: ready
      run: |
        git checkout ${{ github.ref_name }}
        fb=$(./.github/workflows/sh/find_pr_branch.sh feature ${{ github.event_path }})
        echo "::set-output name=issue-no::${fb#feature/}"

    - name: Create temp branch
      id: temp
      if: ${{ steps.ready.outputs.issue-no != '' }}
      run: |
        tmpb=dev-tmp/${{ steps.ready.outputs.issue-no }}
        git push origin $tmpb -d --quiet || :
        git checkout -b $tmpb
        echo "::set-output name=branch::$tmpb"

    - name: Revise comments
      if: ${{ steps.ready.outputs.issue-no != '' }}
      uses: begyyal/act_revise_comments@v1
      with:
        prefix: "#${{ steps.ready.outputs.issue-no }}"
        branch: ${{ steps.temp.outputs.branch }}

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Build with Gradle
      run: |
        chmod +x ./cmd/gradlew
        ./cmd/gradlew build -b ./lib/build.gradle
        ./cmd/gradlew build -b ./cmd/build.gradle

    - name: Test
      run: ./test.sh

    - name: Push dev-tmp
      id: code-update
      if: ${{ steps.ready.outputs.issue-no != '' }}
      run: |
        applied=$(git diff --exit-code --ignore-cr-at-eol --ignore-space-at-eol --quiet || echo 1)
        [ -z $applied ] || (git add . && git commit -m "BY-CI")
        echo "::set-output name=applied::${applied}"
        git push origin HEAD

    - name: Mark success of status checks
      id: status-checks
      if: ${{ steps.ready.outputs.issue-no != '' }}
      run: |
        head=$(git log --pretty=oneline | head -n 1 | cut -d ' ' -f 1)
        echo "::set-output name=head::${head}"
        curl \
          -X POST \
          -H "AUTHORIZATION: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${head} \
          -d '{"state":"success","context":"ci-passed"}'

    - name: Await sequentially
      uses: begyyal/act_await_workflow_runs@v1
      with:
        workflowName: CI

    - name: Push dev if needed
      id: push-dev
      if: ${{ steps.code-update.outputs.applied != '' }}
      run: |
        git checkout ${{ github.ref_name }}
        git cherry-pick ${{ steps.status-checks.outputs.head }}
        git push origin ${{ github.ref_name }} || conflict=1
        echo "::set-output name=conflict::$conflict"

    - name: Handle conflict
      id: handle-conflict
      if: ${{ steps.push-dev.outputs.conflict != '' }}
      run: |
        git checkout ${{ steps.temp.outputs.branch }}
        git reset --hard HEAD^
        head=$(git log --pretty=oneline | head -n 1 | cut -d ' ' -f 1)
        echo "::set-output name=head::${head}"
        curl \
          -X POST \
          -H "AUTHORIZATION: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${head} \
          -d '{"state":"success","context":"ci-passed"}'

    - name: Push master
      run: |
        head=${{ steps.handle-conflict.outputs.head }}
        [ -z "$head" ] && head=${{ steps.status-checks.outputs.head }} || :
        [ -z "$head" ] && head=${{ github.sha }} || :
        branch=${{ steps.temp.outputs.branch }}
        [ -z "$branch" ] && branch=${{ github.ref_name }} || :
        git fetch
        git checkout -f master
        git cherry-pick $(git log $branch ${{ github.event.before }}..$head --pretty=oneline | cut -d " " -f 1 | tac)
        git push origin master

    - name: Termination
      if: always()
      run: |
        tmpb=${{ steps.temp.outputs.branch }}
        [ -n "$tmpb" ] && git push $tmpb -d || :
