name: CI

on:
  push:
    branches: [ develop ]

jobs:

  dev-ci:
    runs-on: ubuntu-latest
    if: ${{ github.token == secrets.GITHUB_TOKEN }}

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: debug
      run: echo ${{ github.actor }}

    - name: Prepare conditions
      id: ready
      run: |
        git config --global user.email "begyyal@gmail.com"
        git config --global user.name "begyyal-ghost"
        fb=$(./.github/workflows/sh/find_pr_branch.sh feature ${{ github.event_path }})
        echo "::set-output name=issue-no::${fb#feature/}"
  
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Build with Gradle
      run: |
        chmod +x ./cmd/gradlew
        ./cmd/gradlew build -b ./lib/build.gradle
        ./cmd/gradlew build -b ./cmd/build.gradle

    - name: Test
      run: ./test.sh

    - name: Revise comments
      if: ${{ steps.ready.outputs.issue-no != '' }}
      run: |
        ./.github/workflows/sh/revise_comments.sh \
          "#${{ steps.ready.outputs.issue-no }}" \
          develop \
          ${{ github.event_path }}

    - name: Rebase to master
      run: |
        head=$(git log --pretty=oneline | head -n 1 | cut -d ' ' -f 1)
        git fetch
        git checkout -f master
        git cherry-pick $(git log develop ${{ github.event.before }}..$head --pretty=oneline | cut -d " " -f 1 | tac)

    - name: Mark success to status checks
      run: |
        head=$(git log --pretty=oneline | head -n 1 | cut -d ' ' -f 1)
        curl \
          -X POST \
          -H "AUTHORIZATION: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${head} \
          -d '{"state":"success","context":"ci-passed-ph2"}'

    - name: Await sequentially
      uses: begyyal/act_await_workflow_runs@v1
      with:
        workflowName: CI

    - name: Push master
      run: |
        git push origin master

    - name: Prepare to close issue
      id: ready-closing
      if: ${{ steps.ready.outputs.issue-no != '' }}
      run: |
        git clone https://github.com/begyyal/act_access_ghra.git
        issue_url_base=${{ github.event.pull_request.issue_url }}
        echo "::set-output name=issue-url::${issue_url_base%/*}/${{steps.ready.outputs.issue-no}}"

    - name: Close issue
      if: ${{ steps.ready.outputs.issue-no != '' }}
      uses: ./act_access_ghra
      with:
        url: ${{ steps.ready-closing.outputs.issue-url }}
        method: 'PATCH'
        args: '{"state":"closed"}'

    - name: Rollback
      if: failure()
      run: |
        git checkout develop
        git reset --hard ${{ github.event.before }}
        token64=$(printf "%s""x-access-token:${{ secrets.PAT_REPO }}" | base64)
        git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $token64"
        git push origin develop -f
