name: push-dev

on:
  push:
    branches: [ dev ]

jobs:

  dev-ci:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
  
    - name: Set up JDK 15
      if: ${{ steps.ready.outputs.issue-no != '' }}
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Build with Gradle
      run: |
        chmod +x ./cmd/gradlew
        ./cmd/gradlew build -b ./lib/build.gradle
        ./cmd/gradlew build -b ./cmd/build.gradle

    - name: Test
      run: ./test.sh

    - name: Await sequentially
      uses: begyyal/act_await_workflow_runs@v1
      with:
        workflowName: push-dev

    - name: Merge
      if: ${{ steps.ready.outputs.issue-no == '' }}
      run: |
        head=$(git log --pretty=oneline | head -n 1 | cut -d ' ' -f 1)
        curl \
          -X POST \
          -H "AUTHORIZATION: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${head} \
          -d '{"state":"success","context":"ci-passed-mst"}'
        git fetch
        git checkout mst
        git merge dev
        git push origin mst

    - name: Rollback
      if: failure()
      run: |
        ./.github/workflows/sh/rollback.sh \
          ${{ github.event_path }} \
          "$(pwd)/.git/" \
          ${{ github.repository }} \
          dev