name: Java CI with Gradle

on:
  push:
    branches: [ develop ]

jobs:

  dev-ci:
    runs-on: ubuntu-latest
    steps:

    - uses: begyyal/act_await_wf_execution@v0.1
      with:
        workflowName: 'Post processing of PR'
        timeoutSec: 1200
    
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./cmd/gradlew

    - name: Build with Gradle
      run: |
        ./cmd/gradlew build -b ./lib/build.gradle
        ./cmd/gradlew build -b ./cmd/build.gradle

    - name: Test
      run: ./test.sh

  push-to-master:
    runs-on: ubuntu-latest
    needs: [ dev-ci ]
    steps:

    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ADMIN_PAT }}
        fetch-depth: 0
        submodules: true

    - name: Setup git condition
      run: |
        git submodule update --remote
        git config --global user.email "begyyal@gmail.com"
        git config --global user.name "begyyal-ghost"

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./cmd/gradlew

    - name: Build with Gradle
      run: |
        ./cmd/gradlew build -b ./lib/build.gradle -x test
        ./cmd/gradlew build -b ./cmd/build.gradle -x test

    - name: Push if needed
      run: |
        git diff --exit-code --ignore-cr-at-eol --ignore-space-at-eol \
        || (git add . && git commit -m "BY-CI" && git push origin HEAD)

    - name: Push to master
      if: success()
      run: |
        git fetch
        git checkout master
        git merge origin/develop
        git push origin master
        
