name: CI

on:
  push:
    branches: [ develop ]

jobs:

  dev-ci:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Prepare conditions
      id: ready
      run: |
        git config --global user.email "begyyal@gmail.com"
        git config --global user.name "begyyal-ghost"
        fb=$(./.github/workflows/sh/find_pr_branch.sh feature ${{ github.event_path }})
        echo "::set-output name=issue-no::${fb#feature/}"
  
    # - name: Set up JDK 15
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '15'
    #     distribution: 'adopt'

    # - name: Build with Gradle
    #   run: |
    #     chmod +x ./cmd/gradlew
    #     ./cmd/gradlew build -b ./lib/build.gradle
    #     ./cmd/gradlew build -b ./cmd/build.gradle

    # - name: Test
    #   run: ./test.sh

    - name: Await sequentially
      uses: begyyal/act_await_workflow_runs@v1
      with:
        workflowName: CI

    - name: Revise and merge
      if: ${{ steps.ready.outputs.issue-no != '' }}
      run: |
        ./.github/workflows/sh/merge.sh \
          "#${{ steps.ready.outputs.issue-no }}" \
          develop \
          ${{ github.event_path }} \
          "$(pwd)/.git/" \
          ${{ secrets.PAT_REPO }} \
          ${{ github.repository }} 

    - name: Merge
      if: ${{ steps.ready.outputs.issue-no == '' }}
      run: |
        head=$(git log --pretty=oneline | head -n 1 | cut -d ' ' -f 1)
        curl \
          -X POST \
          -H "AUTHORIZATION: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${head} \
          -d '{"state":"success","context":"ci-passed-ph2"}'
        git fetch
        git checkout master
        git merge develop
        git push origin master

    - name: Prepare to close issue
      id: ready-closing
      if: ${{ steps.ready.outputs.issue-no != '' }}
      run: |
        git clone https://github.com/begyyal/act_access_ghra.git
        issue_url_base=${{ github.event.repository.issues_url }}
        echo "::set-output name=issue-url::${issue_url_base%/*}/${{steps.ready.outputs.issue-no}}"

    - name: Close issue
      if: ${{ steps.ready.outputs.issue-no != '' }}
      uses: ./act_access_ghra
      with:
        url: ${{ steps.ready-closing.outputs.issue-url }}
        method: 'PATCH'
        args: '{"state":"closed"}'

    # - name: Rollback
    #   if: failure()
    #   run: |
    #     git checkout develop
    #     git reset --hard ${{ github.event.before }}
    #     git push origin develop -f
